### ISSUE TITLE
Release Latest Version

### ISSUE THREAD

**Issue by thatskyz** [jessetane/queue#101]
Hello,

I am using `queue` in my project, but the current latest version of queue on npm does not work, can you please release the latest version onto npm? It works fine when I install from the git repo directly.

Thank you!

**Comment by jessetane** [comment]
@MaksimLavrenyuk is there anything else you think we should do or are we ready to cut 7.0.0?

**Comment by jessetane** [comment]
Please go ahead if you'd like to do it or send a PR. The way I have done it in the past is first with a commit that bumps the version (according to semver of course) in package.json, then I add a tag that exactly matches the version e.g. `git tag 7.0.0` and push both using `git push origin master --tags`. See https://github.com/jessetane/queue/tags for other examples. Once we get a release in place here I will take care of publishing to npm.

**Comment by jessetane** [comment]
@thatskyz thanks for the heads up, we'll get this taken care of asap - currently in the process of bringing our new maintainer up to speed!

**Comment by jessetane** [comment]
Ooh @MaksimLavrenyuk we should add a release note in the readme

**Comment by jessetane** [comment]
Ok, went ahead and released `7.0.0` here and to npm. Note that an API change was made (in the time since this issue was opened) to the start method so its behavior is a bit more idiomatic when a promise is returned.

**Comment by MaksimLavrenyuk** [comment]
@jessetane 
I apologize for the delay. Since I do not have access to my npm account, I was not able to upload the new version immediately. Maybe we should set up a github action to publish versions to npm? This way you will lock your data behind the secrets variable in github and I can publish patches and new versions to npm.

**Comment by jessetane** [comment]
@MaksimLavrenyuk no worries, I just found a few last issues looking at it again today and decided to go ahead and release as I hadn't heard back. A gh action sounds cool but I'd like to continue handling publishing to npm for the time being. Just ping me when you land releases here as described and I'll do a final review before publishing. Nothing personal, it's just that given the number of dependent packages, the blast radius is fairly large if something were to go wrong and my name would be on the line. If having me review becomes a big bottleneck or we need to bring on more maintainers or some other need arises, I'm definitely open to getting something figured out to address sharing the publishing rights.
