### ISSUE TITLE
cb() or return?

### ISSUE THREAD

**Issue by gbell12** [jessetane/queue#11]
I have a job which has steps which use callbacks which might have errors.

For example, this is in my queued job function:

````
function worker(i) {
    var index = i;
    return function(cb) {
        var fs = require('fs');
        var fname = files[index];
        fs.readFile(fname, function(error, source) {
            if (error) {
                console.log("ERROR:" + error);
                // And now???
            }
    }
}
````
1) I'm trying to get local/unique instances of fs (and i) to avoid closures and the resulting clobbering of the same object.  Will queue be OK with this way of doing it?

2) What should I do at the "and now" part?  I'm pretty sure I need to call cb.  Does execution ever continue *after* the call to cb, in which case I'd need a return?  Or is `return cb();` smart?

I fear these are more JS questions than queue questions, so feel free to just close the issue if I should be RTFM'ing.

**Comment by jessetane** [comment]
1) You probably have to close around the file names somewhere so that when data comes back you know where it came from.

2) Calling cb() is not "smart" - if you don't return afterwards, your job could end up running code after the queue has ended.

Maybe try something like this:

``` javascript
var fs = require('fs')
var queue = require('queue')

var files = [ 'a', 'b', 'c' ]
var q = queue()
var data = {}

files.forEach(function (name) {
  q.push(function (cb) {
    fs.readFile(name, 'utf8', function (err, file) {
      if (err) return cb(err)
      data[name] = file
      cb()
    })
  })
})

q.start(function (err) {
  console.log(err, data)
})
```

Note that by using forEach to loop, you get a closure around `name` automatically.

**Comment by gbell12** [comment]
Ah, thanks so much Jesse.  For the module and for the tutorial support.

>Calling cb() is not "smart"...

But you call cb at both exits point from the job in your example...

**Comment by jessetane** [comment]
Calling cb is how you tell the queue when a job is done (whether an error was encountered or not), so you should always call cb exactly once per job.

**Comment by gbell12** [comment]
Right.  Understood.  

FWIW, it's all working - to add to the confusion my workers are using uglify which is synchronous.  So *that's* wrapped in a setInterval.  Everything got clearer when I put all the file handling in its own function, so my call to cb() is very clearly after that function returns.  I'm probably not handling errors well within that function, but gotta save some polishing for tomorrow.  Whether I'll have any idea what's going on in 6 months is another issue!

Runtime down from 2.5 hours to 57 minutes, thanks to queue and child_process.exec.

Thanks again.
