### ISSUE TITLE
Queue stops when no job left

### ISSUE THREAD

**Issue by niahoo** [jessetane/queue#12]
Hi, 

Is it normal that when all jobs are done, the queue stops ? Basically if jobs do not come as fast as they are executed, I must call `q.start()` whenever I use `q.push()`.

Thank you

**Comment by jessetane** [comment]
Yes, that's generally what I use the library for. If you are just using queue for concurrency control and don't care about when the jobs are all finished, calling start after each push shouldn't hurt anything.

**Comment by niahoo** [comment]
Ok thanks !
