### ISSUE TITLE
queue callback doesn't get executed

### ISSUE THREAD

**Issue by iam-peekay** [jessetane/queue#13]
Hi, I'm having trouble understanding why queue won't execute. My code is below: 
```javascript
socket.on('raw', (frame) => {
  q.push((cb) => {
    console.log('got here');

    const src = blobToImage(frame.image);
    if (!src) return;
    let replaced = false;
    const img = document.createElement('img');
    img.src = src;

    img.onload = () => {
      if (!replaced) {
        const canvas = document.createElement('canvas');
        canvas.width = emuWidth;
        canvas.height = emuHeight;
        image.replaceWith(canvas);
        replaced = true;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, frame.x, frame.y);
      }

      cb();
    };
  });
});


// get notified when jobs complete
q.on('success', (result, job) => {
  console.log('job finished processing:', job.toString().replace(/\n/g, ''));
});

// begin processing, get notified on end / failure
q.start((err) => {
  if (err) {
    throw new Error();
  }
  console.log('all done');
});
```

I can see that the socket's "raw" event comes in (I've console.logged it and the frame is there) but the queue never begins. I know this because the console.log in the queue is never run. 

Would love any insight into what might be wrong? Couldn't find any related issues on SO so I apologize for bothering you through a pull request.

**Comment by jessetane** [comment]
For one thing `cb` must be called in every job. For example if the condition in this line is ever met:
``` javascript
if (!src) return;
```
the job would never finish.

But more generally, without some way of knowing how many jobs you will be running in total, how can you know when you are "done"?

**Comment by iam-peekay** [comment]
@jessetane thanks for the quick response. The jobs in this case get added with each new frame coming in. We would only know that the jobs are "done" when all jobs are taken off the queue.

I'm a bit confused by your question. Sorry if i misunderstood. is the implementation missing a detail that I am overlooking?

**Comment by jessetane** [comment]
I guess my idea of queue is that it is an array you fill with jobs, which you then "start", and get notified about when everything is done or something breaks. Sort of like [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) but for callbacks and with concurrency control.

If the socket has an end event you could defer starting the queue until then, or if the socket is staying open indefinitely you shouldn't need anything special - maybe an error handler on the img?

**Comment by jessetane** [comment]
by anything special, I mean you shouldn't need queue at all

**Comment by iam-peekay** [comment]
@jessetane thank you! yes, i agree. appreciate the quick response. I'll close this issue.
