### ISSUE TITLE
Transfer tasks from one queue to another queue safely

### ISSUE THREAD

**Issue by bluejamesbond** [jessetane/queue#14]
What is the suggested way of doing this?

**Comment by jessetane** [comment]
Can you provide some code to demonstrate what you're trying to do?

**Comment by bluejamesbond** [comment]
2 queues; A and B with tasks
A hits a hiccup; transfers all tasks to B
B starts slowing down; transfers tasks back to A

**Comment by jessetane** [comment]
How about using the timeout feature?

**Comment by bluejamesbond** [comment]
I agree the timeout could be effective but I would like to transfer out tasks from one queue to another. Is this possible?

**Comment by jessetane** [comment]
I don't think it's currently possible to transfer a running job between two queues.

**Comment by jessetane** [comment]
Either way, in your example you can still get stuck, right? I think you might just be delaying the inevitable in a complicated way. The simple solution is to consider jobs that time out as failed and to either restart or discard them, or to roll with `concurrency === Infinity`.

**Comment by jessetane** [comment]
I'm not sure it makes sense, but if you wanted to have some secondary limit for slow jobs, you could do something like upping the concurrency in the timeout handler, and reducing it again when the job finishes.

**Comment by bluejamesbond** [comment]
I wanted to transfer jobs that haven't started

**Comment by jessetane** [comment]
That you can do - use one of these methods borrowed from Array: https://github.com/jessetane/queue/blob/master/index.js#L21

**Comment by bluejamesbond** [comment]
Thanks! So if I just splice the array, it will ensure that running tasks won't be included?

**Comment by jessetane** [comment]
Jobs are shifted from the queue internally just before they are run, so yes.

**Comment by bluejamesbond** [comment]
Thanks!
