### ISSUE TITLE
Should timeoutId be unref()'ed?

### ISSUE THREAD

**Issue by maxwellhadley** [jessetane/queue#18]
Currently, a queue with a timeout will keep the event loop running until the timer times out, even though the rest of the application has terminated normally. I hit this running unit tests using Jasmine on an application that I've just modified to use queue. All the tests terminate normally, but they are followed 10 seconds later by my timeout callbacks displaying console.log messages.

I've added `timeoutId.unref();` at line 99 of `index.js` and this stops the callbacks from appearing after the tests finish, and it doesn't _seem_ to have any ill effects on my application.

Is this really a good idea? Or am I making a courageous decision?

Max

**Comment by jessetane** [comment]
Hm.. so you know you're done, but still have outstanding callbacks? That seems unusual, any idea why that would be? Or if I'm misunderstanding, perhaps you can send some example code or better still, a failing test case?

**Comment by maxwellhadley** [comment]
OK, some background:
I'm a maintainer of the npm package [rfxcom](https://www.npmjs.com/package/rfxcom) which interfaces to the [universal home automation wireless transceiver](http://www.rfxcom.com/epages/78165469.sf/en_GB/?ObjectPath=/Shops/78165469/Categories) made by the company of the same name. This lets you send commands to wireless sockets, blinds controllers, lighting dimmers etc, and to receive messages from controllers & sensors of different types. It connects via USB, implemented using an FTDI USB-to-serial chip.

To send a command, you write a short packet to this 'serial port'. The transceiver decodes the packets, checks that nothing else is transmitting, sends the radio message in the correct format, then returns a 'transmitted OK' packet over the 'serial port'. Depending on how busy the channel is, and the exact format of the transmission, it can take a few seconds for the 'transmitted OK' packet to be returned (each command has a command number byte, and the associated 'transmitted OK' packet has the same number). There is an internal command buffer, but this is of limited size, and there is no link-level handshaking in the USB serial link to prevent it being overrun.

Recently a package user has reported an issue which I traced to buffer overrun - they are sending a burst of about 40 commands as soon as the application starts up. To fix this, I have implemented a transmit message queue in my package, using your queue package (which does exactly what I want). I'm using a concurrency of 3 and a timeout of 10,000ms. Each 'job' pushed to the queue when run saves its callback in array indexed by the message number, and transmits the command packet. When the 'transmitted OK' packet is received, I look up the correct callback in the array and call it to complete the job. This is now working fine. However, it can happen that the 'transmitted OK' packet is never received, possibly because packet synchronisation is lost (either to or from the transceiver) or more likely, the USB cable is unplugged. If the cable is unplugged, I handle the event emitted by the serialport and among other things call end() on the queue. In the case of lost synchronisation, I just wait for the timeout to expire and send the next command.

However, calling end() does not cancel the timeout timer object, and since it is ref'ed it will prevent the queue object from being garbage collected, until it times out. Since I'm using only a short timeout, this is no big deal, since it happens only in circumstances when we have lost communication with the transceiver, but it does impact unit testing. Each test that results in a command being sent to my 'fake' serialport creates a timer, and although all the unit tests complete OK, the test script only finishes when they have all timed out.

In my application, unrefing the timer does not seem to have any ill effects, and it makes the test script finish promptly. But I'm aware I'm not using queue in quite the way it was intended, and there may be problems I haven't considered. Maybe they are obvious to you?

**Comment by jessetane** [comment]
Thanks for the additional detail. Clearing the timeout immediately after setting it (if that is what you're doing) seems like it would just prevent the timeout from ever working. If you don't need that feature, just don't pass that option to queue in the first place.

It sounds to me like you actually DO want the timeout feature, and it's just that you want `q.end` to do a better job of cleaning up. I would welcome a PR that changes how `end` works to solve this problem! Please start with a failing test case, it should be trivial to write and make the issue crystal clear. If you're not sure what the best fix is, it will also give us a chance to discuss possible fixes before spending a lot of time on it.

**Comment by jessetane** [comment]
One other thing:

> Each 'job' pushed to the queue when run saves its callback in array indexed by the message number, and transmits the command packet. When the 'transmitted OK' packet is received, I look up the correct callback in the array and call it to complete the job.

Queue already does this tracking of the callback - you should be able to just put the user's callback in or wrap it.

**Comment by jessetane** [comment]
I realize now that unref doesn't actually cancel the timer, so I see why it would work as expected for your use case - pardon my ignorance! I do need this module to work in the browser though where unref usually won't exist. I suppose you could check to see if that method is defined before using it, but I still think the proper solution is to change end to clear any outstanding timers. What do you think?

**Comment by maxwellhadley** [comment]
I've now worked around my immediate problem with the Jasmine tests by explicitly calling the queue callback from an afterEach() function following each test - I can do this because I'm saving the queue callbacks in an array which is a property of the underlying communication object each test uses. It's all rather opaque but it does work, and the test suite now completes in 0.2s instead of 10.2s!

See https://github.com/rfxcom/node-rfxcom for the gory details, especially lib/rfxcom.js - the master branch now includes my queue implementation.

I'm still wondering if the timer ought to be unref'ed. in nodeJS, unlike in a browser, the global object will not go away if there are timers still waiting to fire, even though no other event sources exist. So the application exit is delayed. All unref() does is to stop this from happening without affecting the timer's normal operation. In my application this would mean that a ^C would exit the application immediately, even if it was waiting for a response from the rfxcom transceiver. Cancelling the timer from end() is probably a good idea too, but because Javascript has no finalisers, you can't guarantee it will always be called.

**Comment by jessetane** [comment]
You do raise some good points - again, happy to look at a pull request if you feel up to it.

**Comment by maxwellhadley** [comment]
I'll put it in the queue...

**Comment by jessetane** [comment]
fixed by c3625b3da80a303340d94c6fdc2110ba85989020
