### ISSUE TITLE
success emit returns an undefined result

### ISSUE THREAD

**Issue by thxmike** [jessetane/queue#20]
Based on the example, I notice when using the event emitter 'success', the "result" is undefined. Is this right? Perhaps, it is something I am doing something incorrectly.

q.on('success', function(result, job) {

        console.log(result);
        console.log('job successful processing:', job.toString().replace(/\n/g, ''));
        console.log(q.length);
        
    })

**Comment by jessetane** [comment]
That would depend on if you're passing anything to the callback.

**Comment by jessetane** [comment]
``` javascript
var q = queue()
q.on('success', result => {
  console.log(result)
})
q.push(cb => cb(null, 42))
q.start()
```

**Comment by thxmike** [comment]
Yeap, I did not see this but this helps. It may be worth a few minutes to add this to the existing example. Thanks.

**Comment by pallix** [comment]
This needs to go in the documentation! What is the purpose of the first argument to `cb`?

**Comment by jessetane** [comment]
The first argument to a callback is always `error`. If you pass an error to any queue callback the queue will end and emit the error. This function is designed to be a generic replacement for the callbacks node APIs accept, such as the one used by [`fs.read`](https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback).

**Comment by jessetane** [comment]
I actually don't find myself using this result passing feature. I just store whatever results I need before calling cb. Such as in the example:
https://github.com/jessetane/queue/blob/master/example/index.js

There are also other libraries that handle result capturing in a more well defined way than queue such as [`run-parallel`](https://github.com/feross/run-parallel).
