### ISSUE TITLE
Concurrency Problem

### ISSUE THREAD

**Issue by thxmike** [jessetane/queue#21]
I am currently using this library to execute three to six concurrent functions at the same time.
It seemed simple enough. However, upon testing I came across the following.  
In a foreach loop, I placed three long running processes in the queue and set the concurrency to one.
I see the first function executes fine but the other instances do not and done is emitted without the other two running. I would assume with a concurrency of one they would run serially but I am not seeing this. I am using version 4.0.0

example:

   var queue = require('queue');
    var queue_options = {
    concurrency: 1
   } 
   
var q = queue(queue_options);
    networks.forEach(function(network){ //this only has three networks
        
        var network_collector =  new Collector(some_library, configuration.something, sql_manager, Promise);
        q.push(function(callback) {

            network_collector.collect(network.IPLocationID, network.FirstOctet, network.SecondOctet)
                .then(function(blah){
                    callback('Successfully completed  ' + blah)
                    console.log(q.length)
                }).catch(function(err){
                    callback('Unsuccessfully completed ' + blah)
                    console.log(err);
            });

        });
        console.log(q.length);
    });

**Comment by jessetane** [comment]
Would it be possible for you to make a test case by replacing the network collector part with a mock up using setTimeout?

Maybe using tonic: https://tonicdev.com/npm/queue

**Comment by thxmike** [comment]
Here you go

File #1 - temp.js
var queue = require('queue');

var Promise = require('bluebird');

var Item_collector = require('./item_collector');

var queue_options = {
    concurrency: 1
}

var q = queue(queue_options);
var item_collection = []
item_collection.push({"ID": 1, "First" : "First", "Second" : "Second"})
item_collection.push({"ID": 2, "First" : "First", "Second" : "Second"})
item_collection.push({"ID": 3, "First" : "First", "Second" : "Second"})

item_collection.forEach(function(item){
    var item_collector =  new Item_collector(Promise);
    q.push(function(callback) {
        item_collector.long_running(item.ID, item.First, item.Second)
            .then(function(message){
                callback('Successfully completed item ' + message)
                console.log(q.length)
            }).catch(function(err){
            callback('Unsuccessfully completed item ' + err)
            console.log(err);
        });
    });
    console.log(q.length);
});

q.on('success', function(result, job) {
    console.log(result);
    console.log('job successful processing:', job.toString().replace(/\n/g, ''));
    console.log(q.length);
})

q.on('error', function(err, job) {
    console.log(err);
    console.log('job error processing:', job.toString().replace(/\n/g, ''));
    console.log(q.length)
});

q.start(function(err) {
    if(err){
        console.log(err);
    }
    console.log('all done:');
})

File #2 - item_collector.js

module.exports = function (Promise){
    var long_running = function (ID, first, second) {
        return new Promise(function(resolve, reject){
            setTimeout(function () {
                console.log('slow job finished');
                resolve('done')
            }, 10000);
        })
    }
    
    return {
        long_running: long_running
    }
}


# package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "temp.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bluebird": "^3.3.5",
    "queue": "^4.0.0"
  }

Let me know if this is enough

**Comment by jessetane** [comment]
@thxmike can you put this into tonic and send me the link instead? I can't read this easily due to the formatting.

**Comment by jessetane** [comment]
Here's the link again: https://tonicdev.com/npm/queue

**Comment by jessetane** [comment]
Also, in general, if you can write a succinct failing test case (this looks a little too complex) best practice is to just fork the library, add the failing test and submit it as a pull request. Travis will run the test and show exactly where the problem is so that everyone can see it easily.

**Comment by jessetane** [comment]
Here is the existing test, for example: https://github.com/jessetane/queue/blob/master/test/synchronous.js

**Comment by jessetane** [comment]
requirebin is cool too if you don't like tonic:
http://requirebin.com/?gist=22553d81e0058d451208faaf2f3cf925

**Comment by thxmike** [comment]
I have tried placing it on Tonic and RequireBin but no-go. Neither support multiple files from what I can tell. 

I have updated the formatting in the previous comment to be more legible.
The first is the main program "temp.js", 
The second is a module that is part of the code that is queued "item_collector.js"
The last file is the "package.json"

This is the best I can do.

**Comment by jessetane** [comment]
I had no trouble putting this into tonic, check it out here:
https://tonicdev.com/575c3c7b175fc4120064aabc/575c729c2c24301200c95d04

It seems to work? What would you expect to happen?

**Comment by thxmike** [comment]
It runs but only the first job. It loads three. 
There should be three "job error processing:" in the output. I only see one. 
BTW, On tonicdev, I am not sure how you added the second and third files. I only see the text of the one.

**Comment by jessetane** [comment]
A simple test case should only need one file... I just put the code all together.

**Comment by jessetane** [comment]
If any job passes an error to it's callback, that's it - the queue is considered done.

**Comment by thxmike** [comment]
I think I see the issue now. Got it. 
Thanks for all your help.
