### ISSUE TITLE
Add job in an async manner

### ISSUE THREAD

**Issue by tnguyen14** [jessetane/queue#27]
Is there a way to start the queue, but add jobs to it in an async manner (at some later point in the future), so the jobs can be executed as and when they arrive in the queue?

**Comment by jessetane** [comment]
sure, you can add jobs to a queue at any time.

**Comment by jessetane** [comment]
if the queue has already ended you would need to call start again.

**Comment by jessetane** [comment]
take a look at #22 also.

**Comment by jessetane** [comment]
Fixed by #28
