### ISSUE TITLE
Pause the queue while processing jobs

### ISSUE THREAD

**Issue by MattOakley** [jessetane/queue#33]
If you use `queue.stop()` while processing jobs it is no effect.

This is because of this code in index.js
           
     if (this.jobs.length > 0) {
       this.start()
     }
Which runs the next job regardless of whether the queue is running or not.

Should this code be?

    if (this.running && this.jobs.length > 0) {
      this.start()
    }

**Comment by jessetane** [comment]
concurrency?

**Comment by jessetane** [comment]
https://github.com/jessetane/queue/blob/master/test/stop.js

**Comment by MattOakley** [comment]
I had concurrency set to 1, and it  still processed the next job after calling stop()

**Comment by jessetane** [comment]
Feel free to send a PR with a failing test

**Comment by jessetane** [comment]
Thanks for pointing this out.

Here is the failing test if you're interested:
https://github.com/jessetane/queue/blob/master/test/stop-sync.js

Published as 4.4.1
