### ISSUE TITLE
How to access functions from module into the queue

### ISSUE THREAD

**Issue by yudao** [jessetane/queue#35]
Hi,

First, thanks for this great little library!

I'm using module in javascript and I'm trying to add a queue function into one of them to prepare a queue of jobs an run it.

This is an example (gist) of my problem:
https://gist.github.com/yudao/6ec09c0e5cd5fa7f9f4755b4db4ce6fd

I've tried many things but I can't access to my vars or function inside the module.

Yu.

**Comment by jessetane** [comment]
Your gist doesn't make sense to me, can you create a runnable example that demonstrates the issue? Perhaps using runkit?
https://npm.runkit.com/queue

**Comment by yudao** [comment]
@jessetane Sorry, it was a problem in my states.

Sorry for disturbing and keep going on good work :) 

Tanks a lot!

Yu.
