### ISSUE TITLE
Understanding behavior

### ISSUE THREAD

**Issue by ScreamZ** [jessetane/queue#41]
Hello, great job !

I'm having issues understanding the purpose of `q.results`... Can you give me an example ?

I also need to serialize my jobs in order to restart them in case of a crash or shutdown and restart,
what do you suggest me as the best solution, knowing that function are not serializable.

It could have been nice that instead of passing function as argument having possibility to pass objects, and one function will be called for each of them as the queue process.

This could allow me to pass params for my jobs to the queue and serialize them, and for each occurence the function i gave is called.

Best regards

**Comment by jessetane** [comment]
> I'm having issues understanding the purpose of q.results... Can you give me an example ?
https://github.com/jessetane/queue/blob/master/test/results.js

> I also need to serialize my jobs in order to restart them in case of a crash or shutdown and restart,
what do you suggest me as the best solution, knowing that function are not serializable.
What are these jobs for? How do you generate them in the first place? Can you not repeat the exercise easily for some reason?

**Comment by ScreamZ** [comment]
I've done some tricks, seems to work well.

I just needed to think another way.

All right, thanks
