### ISSUE TITLE
job doesnt finish synchronously 

### ISSUE THREAD

**Issue by lakshaygaur** [jessetane/queue#43]
Hi , Im pushing multiple jobs in queue using a for loop but the whole execution itself is running asynchronously. I dont think queue jobs are supposed to work this way. Below is the code screenshot and response.
![queue-problem](https://user-images.githubusercontent.com/26569986/39822218-a9625198-53c7-11e8-82ca-41b5447a1461.png)

**Comment by jessetane** [comment]
please send a pr with a failing test, or at the very least a complete example that demos your issue - as succinct as you can make

**Comment by jessetane** [comment]
use https://npm.runkit.com/queue maybe?

**Comment by saan099** [comment]
Functionalities aren't meant to be synchronous themselves, only suppose to start the execution in a synchronous manner. Use npm sync-queue package instead.

**Comment by jessetane** [comment]
er, ok closing I guess, reopen if you need to
