### ISSUE TITLE
Queue ends when individual job is failed/Errored

### ISSUE THREAD

**Issue by LTPrashant** [jessetane/queue#44]
As of now the implementation is such that even when a single job is failed queue ends. In my case the Jobs are independent and i want to keep processing the remaining jobs. Any idea how can i achieve it?
Also is there any particular reason that the queue ends even on single Error.

**Comment by jessetane** [comment]
> As of now the implementation is such that even when a single job is failed queue ends. In my case the Jobs are independent and i want to keep processing the remaining jobs. Any idea how can i achieve it?

Sure:
``` javascript
q.push(cb => {
  doAsyncThing(err => {
    if (err) console.error(err)
    cb() // invoke callback without passing an error
  })
})
```
> Also is there any particular reason that the queue ends even on single Error.

It's just the behavior I usually want?

**Comment by LTPrashant** [comment]
Got it. Thanks

**Comment by bugs181** [comment]
Has the behavior of this changed? If so, it was not documented anywhere. I want to ensure that the queue will continue even if a task has failed. We have plenty of events such as `error` and `timeout` to figure out what to do in those cases.
