### ISSUE TITLE
queue stop/end doesn't work

### ISSUE THREAD

**Issue by tasoss** [jessetane/queue#45]
Hello.It's a little bit strange but after a while i have tried for the first time to use 
stop/end and it doesn't work.I mean it just keeps going on.
Using node v8.11.2 on ubuntu 16.0.4
Thanks!

**Comment by jessetane** [comment]
can you share a minimal example that demonstrates your issue? maybe try using https://npm.runkit.com/queue ?

**Comment by tasoss** [comment]
Thanks for replying.I would like to ask you.If i have set autostart:true and i call stop.Then when adding a new job does it start automatically?Because this seems to be my case.I'm now using autostart false and it seems to be working find...(i mean stop/end works as expected).So does it work by design like this?

**Comment by jessetane** [comment]
Argh missed this, sorry for the delay. `autostart` should be false by default, and I believe you're correct that while a call to `stop` will pause an autostarted queue, any additive method will start it again automatically. I _think_ this behavior makes sense, but feel free to push back on that.

**Comment by tasosss** [comment]
Hello again.I'm delayed too :-p
Well after a few iterations my queue is not processed and i don't know how to create an example for that.What i'm trying to say is that 

> autostart should be false by default, and I believe you're correct that while a call to stop will pause an autostarted queue, any additive method will start it again automatically

this doesn't work as expected , but again i have to show you an example :)

Moreover in another scenario myqueue.jobs is an empty array but q.length is 1 with pending 1.
What am i missing here?

**Comment by jessetane** [comment]
Hm, without an example it's really hard to help...

**Comment by tasosss** [comment]
Of course.
Thanks again.

**Comment by bugs181** [comment]
> while a call to `stop` will pause an autostarted queue, any additive method will start it again automatically.

I don't believe this should happen. I believe a "manual" method of control (in this case `stop`) should be followed by another manual method of intervention (such as `start`). Personally, I love having `autostart` option so I don't have to manually call `start` every time I add new items to the queue. But occasionally, I want to "pause" processing (i.e. from a UI) until something else happens.
