### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by hackhat** [jessetane/queue#51]
I just did:

    import * as queue from "queue";
    const _queue = queue({concurrency: 50, autostart: false});

Error:

TSError: ⨯ Unable to compile TypeScript:
../x/x/upload.ts(52,18): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof im
port("/node_modules/queue/index")' has no compatible call signatures.

I'm confused.. as this has ts libs. I've used many ts libs, but this one doesn't work.

I tried:

    import queue from "queue";

**Comment by jessetane** [comment]
I don't know Typescript, maybe @T4cC0re can help?

**Comment by hackhat** [comment]
I managed to do with `require("queue")`, but that's not using the `import` keyword. Ok, let me know when somebody knows this. I think something is wrong in the typescript definition...

**Comment by joelgriffith** [comment]
Have you tried updating your TS config with `allowSyntheticDefaultImports`? This should allow you to do `import queue from 'queue'`

**Comment by hackhat** [comment]
I didn't but I think it just does the same as `import * as queue from "queue";`. I don't have the project here.

**Comment by sdavispostmedia** [comment]
Did anyone have anymore thoughts on this? I have the same issue.

**Comment by hackhat** [comment]
Solved here: https://stackoverflow.com/questions/52940221/proper-usage-of-cucumber-with-typescript

**Comment by AndrewJDR** [comment]
@hackhat 
I am getting the same error described in your original post on this issue. Can you describe exactly what you did to fix the issue (in terms of how you tweaked the `import` statement etc)? That problem with that thread you linked is that it is a hodgepodge of a bunch of different things, and it's not clear how it relates to getting `queue` to work with typescript.

Alternatively, perhaps @Codex- who worked on the typings most recently can chime in?

**Comment by Codex-** [comment]
Hey @AndrewJDR 

Have a look at the tests for the typings to see how to import these:
https://github.com/jessetane/queue/blob/master/index.test-d.ts

```ts
import Queue, { Options, QueueWorker, QueueWorkerCallback } from 'queue';
```

I can't check this properly at the moment, returning from Japan next week though and can take another look then if you're still having trouble.
