### ISSUE TITLE
Missing `events` dependency?

### ISSUE THREAD

**Issue by nossbigg** [jessetane/queue#56]
Is this package missing the `events` dependency? 

Seems like this library uses the `events` library here:
https://github.com/jessetane/queue/blob/5f119432ea763863010aeb804702b0100a516ddd/index.js#L2

I had to install `events` as my project's dependency (note: not devDependency) to make this library work. Small issue, but I wonder if it's affecting anyone else?

EDIT: I was running this library in a `react-native` project, thus it was missing the `events` library that comes with node. Perhaps it would be useful to add to the README.md to indicate that users need to install `events` (the one maintained by Gozala [here)](https://github.com/Gozala/events) for non-Node environments?

**Comment by jessetane** [comment]
I suppose it depends on your build tool and whether it tries to provide a "node-like" environment out of the box - I use browserify and so haven't run into this particular issue.

Generally I like explicitly declaring deps but I wonder if we risk accidentally pulling in multiple copies of the events module? Open to advice.

**Comment by jessetane** [comment]
If nothing else, like you say, a note in the readme. Patches welcome.

**Comment by nossbigg** [comment]
> Generally I like explicitly declaring deps but I wonder if we risk accidentally pulling in multiple copies of the events module? Open to advice.

With you on this. It'd be bad if users had no way to exclude the `events` dependency if they were operating in an environment that already has that dependency. 

I'll add a note to the README on this point. Raised #57 for this, please take a look :)
