### ISSUE TITLE
Queue of Queues 

### ISSUE THREAD

**Issue by aymengraoui** [jessetane/queue#68]
hello, 
thanks for the module i started using it about 3 days ago and im having so much fun with it, 
the thing is i wanna make a BIGQueue for multiple MINIQueues and im gonna use the UI to pause and start the MINIQueues inside the BIGQueue but im stuck in a position where i dont know the index of the MINIQueues.
thanks

**Comment by balupton** [comment]
Perhaps https://github.com/bevry/taskgroup would suite your needs

**Comment by jessetane** [comment]
@aymengraoui can you post some simple example code that demonstrates the issue?

**Comment by aymengraoui** [comment]
hey guys 
sorry for taking too long to response i was working on that and i managed to make it work 
`let itemQ= Queue({
      autostart: false,
      concurrency: 1
    })
// 
//   fill the itemQ
//
QueueOfItems.push(next => {
      updateListOfDownloads(Item.Id, DownloadStatus.DOWNLOADING)
      eventCatcher.on('PauseDownload', (id) => {
        if (item.Id === id) {
          updateListOfDownloads(id, DownloadStatus.PAUSED)
          itemQ.stop()
        }
      })
      eventCatcher.on('ResumeDownload', (id) => {
        if (item.Id === id) {
          updateListOfDownloads(id, DownloadStatus.DOWNLOADING)
          itemQ.start()
        }
      })
      eventCatcher.on('CancelDownload', (id) => {
        if (course.Id === id) {
          itemQ.end()
        }
      })
      itemQ.start((err) => {
        if (err) throw err
        updateListOfDownloads(course.Id, DownloadStatus.FINISHED)
        next()
      })
    }`
thank you
