### ISSUE TITLE
Autostart and concurrency causes jobs to not run if end() is used

### ISSUE THREAD

**Issue by veddermatic** [jessetane/queue#69]
It seems that if you have autostart set, then call `end()` , then add more jobs to the queue, it will only ever process up to `concurrency` of them. Example:

```
const requestQ = Queue({ concurrency: 3, autostart: true });

const queueNewStuff = items => {
  console.log("adding %s items", items.length);
  requestQ.end();
  items.forEach( item => {
   console.log("adding item %s", item.id");
    requestQ.push( () => console.log("queue handled %s", item.id) );
  });
}

const initialItem =  {id: 1, name: "a"},
console.log("adding item %s", initialItem.id");
requestQ.push( () => console.log("queue handled %s", initialItem.id) ); 


const items = [
  {id: 2, name: "b"},
  {id: 3, name: "c"},
  {id: 4, name: "d"},
  {id: 5, name: "e"},
  {id: 6, name: "f"},
]
queueNewStuff( items );
```

When this is run, you'll see roughly this:

```
adding item 1
queue handled 1  // the manually added item is run as expected

adding 5 items  // we are adding this many to the queue
adding item 2  // adding our jobs...
adding item 3
adding item 4
adding item 5
adding item 6

queue handled 2 // queue running jobs...
queue handled 3
queue handled 4

// ... where did 5 and 6 go?
```

If I change `concurrency` to 5, all the job are run. (But if I add a 6th item, it won't be)

Is this expected behavior? If so, what can I do to mitigate this? My use case is that users can click on items in a sidebar and I queue requests based on that. However, if they change a value elsewhere, I want to stop any new requests and add a new batch of them, thus my wanting to call `end()` and then re-add a bunch of items.

**Comment by veddermatic** [comment]
I also just tried not using auto-start and manually calling `start()` every time I add items, and I see the same behavior. If I turn off concurrency, it works as expected, so it looks like autostart is not related.

**Comment by jessetane** [comment]
Autostart just calls start for you automatically any time you call an additive array method (like push). 

The main problem with your example is that you don't execute the callbacks passed to your jobs. It's fine if your jobs complete synchronously (but why use this library then?), you still need to execute the callbacks though or the queue thinks your jobs are still running.

**Comment by veddermatic** [comment]
You are correct! I was using it in other places and returning Promises, but in a new part of my app I was just calling plain old functions, and so my brain glossed over the callback bit because I hadn't needed to prior.
