### ISSUE TITLE
Stop task after 'timeout'?

### ISSUE THREAD

**Issue by borsTiHD** [jessetane/queue#70]
Hi,

i'm really confused right now.
Is there a way to stop my task after it runs in timeout?

My actual behaviour:
I put my function in the queue.
My task starts running and after the timout (for example, I set a timeout for 5 seconds, my task will definitely run out), the `q.on('timeout', ..)` event gets called.

Strangely, my task still runs in the background and could successfully finished.
Is there a way to stop my task at this point?

What excatly can I do with the `job` parameter on the event?
That excatly do the `next()` function in the parameter? 
Just going to the next task in queue?

And additionaly.
My tasks are stored in an higher class object (for example: `this.apiCall[uniqueKey].task` and push it in the queue with `q.push(this.apiCall[uniqueKey].task)`).
Is there a way to access that object after a 'timeout' event occurs?
I want to achive something like this:

```
this.apiCall[uniqueKey].task = (done) => {
  // do some stuff...
  done()
}

q.push(this.apiCall[uniqueKey].task)

q.on('timeout', (next, job) => {
  console.log('job timed out:', job.toString().replace(/\n/g, ''))
  const err = new Error('timeout')
  this.catchError(err, this.apiCall[uniqueKey].requestObject) // handles errors and put infos in the gui
  stopJob()
  next()
})
```

Thanks in advanced. :)

greetings
borsTiHD

**Comment by jessetane** [comment]
how about something like this:

```
var apiCall = this.apiCall[uniqueKey]

apiCall.cancel = () => {
  // cancel somehow
}

apiCall.task = done => {
  // do some stuff...
  done()
}

apiCall.task.ref = apiCall

q.push(apiCall.task)

q.on('timeout', (next, job) => {
  console.log('job timed out:', job.toString().replace(/\n/g, ''))
  var apiCall = job.ref
  const err = new Error('timeout')
  this.catchError(err, apiCall.requestObject) // handles errors and put infos in the gui
  apiCall.cancel()
  next()
})
```

**Comment by borsTiHD** [comment]
Oh I didn't know you can add stuff to a function.
I use 'abort-controller' for aborting. Adding a 'ref' was the key. :D
Thank you so much, it works perfectly.
