### ISSUE TITLE
Release latest?

### ISSUE THREAD

**Issue by joelgriffith** [jessetane/queue#76]
Hey! Happy 2021! I recently had a fix PR https://github.com/jessetane/queue/commit/321fe6e45251b88576e96cc006ae1f7ead7122e4 that's been merged for a while, but not release. Care to do a package release?

**Comment by jessetane** [comment]
Sorry about that, thanks for the reminder. 6.0.2 should be live now.

**Comment by joelgriffith** [comment]
Thanks!!
